### ISSUE TITLE
Undocumented use of physt library

### ISSUE THREAD

**Issue by janpipek** [brenthuisman/phd_tools#1]
Hi Brent, 

found out you're including almost entirely my library `physt` inside your repo. It's cool that you are using it - I am happy for every user. However, it would be nice if you could either write some acknowledgement, link the original library... Or, probably best, to use it as external dependency and collaborate on the original repo.

Regards,
Jan

**Comment by brenthuisman** [comment]
Hey Jan,

Oops, I havn't pushed to that repo in a while because I ported it to Python 3 and use that version now (it's not on GH, yet). I actually never got around to using physt, and I have removed it a while ago (from this 'old' version as well). I'll push an update removing your lib asap.

Cheers,
Brent

**Comment by janpipek** [comment]
Thanks. But don't take me wrong, I will be happy if you use physt :-)

Cheers,
Jan

**Comment by brenthuisman** [comment]
I remember it looked very interesting, which is why I dumped it wholesale into my plot dir, such that I wouldn't forget. But in the end I solved things with tweaks to what I had already, which means I understand fully (sorta) what's going on, which is a nice plus ;)

Cheers,
Brent
